---
# Ansible inventory for CoinbaseChain multi-network deployment
# 6 nodes running regtest, testnet, and mainnet networks on same hardware

all:
  children:
    # Regtest Network - Fast testing with 2-minute blocks
    coinbasechain_regtest:
      hosts:
        ct20:
          ansible_host: 178.18.251.16
          node_id: 0
          p2p_port: 29590
        ct21:
          ansible_host: 185.225.233.49
          node_id: 1
          p2p_port: 29590
        ct22:
          ansible_host: 207.244.248.15
          node_id: 2
          p2p_port: 29590
        ct23:
          ansible_host: 194.140.197.98
          node_id: 3
          p2p_port: 29590
        ct24:
          ansible_host: 173.212.251.205
          node_id: 4
          p2p_port: 29590
        ct25:
          ansible_host: 144.126.138.46
          node_id: 5
          p2p_port: 29590
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/mykey
        ansible_python_interpreter: /usr/bin/python3
        coinbasechain_network: regtest
        coinbasechain_version: latest
        docker_data_dir: /var/lib/coinbasechain/regtest
        container_name: "coinbasechain-regtest"

    # Testnet Network - 10-minute blocks
    coinbasechain_testnet:
      hosts:
        ct20:
          ansible_host: 178.18.251.16
          node_id: 0
          p2p_port: 19590
        ct21:
          ansible_host: 185.225.233.49
          node_id: 1
          p2p_port: 19590
        ct22:
          ansible_host: 207.244.248.15
          node_id: 2
          p2p_port: 19590
        ct23:
          ansible_host: 194.140.197.98
          node_id: 3
          p2p_port: 19590
        ct24:
          ansible_host: 173.212.251.205
          node_id: 4
          p2p_port: 19590
        ct25:
          ansible_host: 144.126.138.46
          node_id: 5
          p2p_port: 19590
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/mykey
        ansible_python_interpreter: /usr/bin/python3
        coinbasechain_network: testnet
        coinbasechain_version: latest
        docker_data_dir: /var/lib/coinbasechain/testnet
        container_name: "coinbasechain-testnet"

    # Mainnet Network - 1-hour blocks (production)
    coinbasechain_mainnet:
      hosts:
        ct20:
          ansible_host: 178.18.251.16
          node_id: 0
          p2p_port: 9590
        ct21:
          ansible_host: 185.225.233.49
          node_id: 1
          p2p_port: 9590
        ct22:
          ansible_host: 207.244.248.15
          node_id: 2
          p2p_port: 9590
        ct23:
          ansible_host: 194.140.197.98
          node_id: 3
          p2p_port: 9590
        ct24:
          ansible_host: 173.212.251.205
          node_id: 4
          p2p_port: 9590
        ct25:
          ansible_host: 144.126.138.46
          node_id: 5
          p2p_port: 9590
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/mykey
        ansible_python_interpreter: /usr/bin/python3
        coinbasechain_network: mainnet
        coinbasechain_version: latest
        docker_data_dir: /var/lib/coinbasechain/mainnet
        container_name: "coinbasechain-mainnet"

    # Combined group for all nodes (useful for common operations)
    coinbasechain_nodes:
      children:
        - coinbasechain_regtest
        - coinbasechain_testnet
        - coinbasechain_mainnet
